-- 1. Tabla de Roles
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE, 
    nombre VARCHAR(50) NOT NULL,        
    descripcion TEXT
);

-- 2. Empresas Internas
CREATE TABLE empresas_internas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL, 
    representante_legal VARCHAR(150),       
    direccion_fiscal VARCHAR(255),          
    activo BOOLEAN DEFAULT TRUE
);

-- 3. Clientes
CREATE TABLE clientes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_interna_id INT NOT NULL REFERENCES empresas_internas(id) ON DELETE RESTRICT,     
    ruc VARCHAR(11) NOT NULL UNIQUE,     
    razon_social VARCHAR(150) NOT NULL,  
    activo BOOLEAN DEFAULT TRUE
);

-- 4. Sedes Operativas
CREATE TABLE sedes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,                 
    nombre VARCHAR(150) NOT NULL,            
    direccion VARCHAR(255),                  
    distrito VARCHAR(100),                   
    contacto_nombre VARCHAR(100),            
    contacto_telefono VARCHAR(20),           
    presupuesto DECIMAL(10, 2) DEFAULT 0.00, 
    activo BOOLEAN DEFAULT TRUE
);

-- 5. Usuarios del Sistema
CREATE TABLE usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL, 
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(150) UNIQUE,
    rol_id INT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    activo BOOLEAN DEFAULT TRUE
);

-- 6. Matriz de Asignación (Supervisores a Sedes)
CREATE TABLE usuario_sedes (
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, sede_id)
);

-- 7. DICCIONARIOS DE DATOS (CATÁLOGOS)
CREATE TABLE cargos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE tipos_documento (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE, 
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE tipos_trabajador (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE bancos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE sistemas_pension (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE, 
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('ONP', 'AFP'))
);

CREATE TABLE regimenes_laborales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE, 
    dias_vacaciones INT NOT NULL        
);

CREATE TABLE modalidades_contrato (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE 
);

-- Ubigeo en formato plano
CREATE TABLE ubigeo_distritos (
    id CHAR(6) PRIMARY KEY,             
    departamento VARCHAR(50) NOT NULL,  
    provincia VARCHAR(50) NOT NULL,     
    distrito VARCHAR(50) NOT NULL       
);

-- 8. GESTIÓN DE PERSONAL
-- 8.1 Ficha Maestra Única (La Persona)
CREATE TABLE personas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento_id INT NOT NULL REFERENCES tipos_documento(id) ON DELETE RESTRICT,
    numero_documento VARCHAR(20) NOT NULL UNIQUE, 
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    sexo VARCHAR(20) NOT NULL CHECK (sexo IN ('Masculino', 'Femenino')),
    fecha_nacimiento DATE NOT NULL,
    direccion VARCHAR(255),
    ubigeo_id CHAR(6) REFERENCES ubigeo_distritos(id) ON DELETE RESTRICT,                     
    telefono VARCHAR(20),
    correo VARCHAR(150),
    
    banco_sueldo_id INT REFERENCES bancos(id) ON DELETE SET NULL,
    cuenta_sueldo VARCHAR(50),
    banco_cts_id INT REFERENCES bancos(id) ON DELETE SET NULL,
    cuenta_cts VARCHAR(50),
    sistema_pension_id INT NOT NULL REFERENCES sistemas_pension(id) ON DELETE RESTRICT,
    codigo_cuss_afp VARCHAR(20),
    
    fecha_ultimo_emo DATE,
    talla_polo VARCHAR(10),
    talla_pantalon VARCHAR(10),
    talla_calzado VARCHAR(10),
    
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 8.2 El Puesto Dinámico (Vínculo Laboral)
CREATE TABLE vinculos_laborales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id INT NOT NULL REFERENCES personas(id) ON DELETE CASCADE,               
    empresa_interna_id INT NOT NULL REFERENCES empresas_internas(id) ON DELETE RESTRICT,       
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE RESTRICT,                  
    cargo_id INT NOT NULL REFERENCES cargos(id) ON DELETE RESTRICT,
    tipo_trabajador_id INT NOT NULL REFERENCES tipos_trabajador(id) ON DELETE RESTRICT,
    lugar_especifico_trabajo VARCHAR(150),
    
    regimen_laboral_id INT NOT NULL REFERENCES regimenes_laborales(id) ON DELETE RESTRICT,
    asignacion_familiar BOOLEAN DEFAULT FALSE,
    sueldo_basico DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    fecha_cese DATE DEFAULT NULL,
    motivo_cese TEXT DEFAULT NULL,
    
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. HISTORIALES Y CONTROL LEGAL
-- 9.1 Historial de Contratos
CREATE TABLE contratos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinculo_laboral_id INT NOT NULL REFERENCES vinculos_laborales(id) ON DELETE CASCADE,
    modalidad_contrato_id INT NOT NULL REFERENCES modalidades_contrato(id) ON DELETE RESTRICT,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE, 
    estado VARCHAR(20) DEFAULT 'Vigente' CHECK (estado IN ('Vigente', 'Vencido', 'Renovado', 'Anulado')),
    archivo_pdf VARCHAR(255), 
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9.2 Control Histórico de Vacaciones
CREATE TABLE vacaciones_historico (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinculo_laboral_id INT NOT NULL REFERENCES vinculos_laborales(id) ON DELETE CASCADE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    dias_calendario INT NOT NULL, 
    notas TEXT,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 10. PIZARRA DIGITAL DE RECLUTAMIENTO
CREATE TABLE solicitudes_personal (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE RESTRICT,
    cargo_id INT NOT NULL REFERENCES cargos(id) ON DELETE RESTRICT,
    turno VARCHAR(50) NOT NULL,
    genero_requerido VARCHAR(20) DEFAULT 'Indistinto' CHECK (genero_requerido IN ('Masculino', 'Femenino', 'Indistinto', 'Mixto')),
    motivo_vacante TEXT,
    plazas_solicitadas INT NOT NULL DEFAULT 1,
    plazas_cubiertas INT NOT NULL DEFAULT 0,
    estado VARCHAR(20) DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Parcial', 'Completado')),
    fecha_solicitud DATE NOT NULL,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 11. DICCIONARIOS LOGÍSTICOS
CREATE TABLE categorias_producto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE, 
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE unidades_medida (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,  
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE proveedores (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    contacto_nombre VARCHAR(100),
    contacto_telefono VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tallas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor VARCHAR(10) NOT NULL UNIQUE,   
    activo BOOLEAN DEFAULT TRUE
);

-- 12. CATÁLOGO CENTRAL Y VARIANTES
CREATE TABLE productos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) UNIQUE,                  
    categoria_id INT NOT NULL REFERENCES categorias_producto(id) ON DELETE RESTRICT,
    unidad_medida_id INT NOT NULL REFERENCES unidades_medida(id) ON DELETE RESTRICT,
    proveedor_id INT REFERENCES proveedores(id) ON DELETE SET NULL,                        
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio_unitario DECIMAL(10, 2) DEFAULT 0.00,
    es_uniforme BOOLEAN DEFAULT FALSE,       
    activo BOOLEAN DEFAULT TRUE,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE producto_tallas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id INT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    talla_id INT NOT NULL REFERENCES tallas(id) ON DELETE RESTRICT,                   
    stock_actual INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_producto_talla UNIQUE (producto_id, talla_id) 
);

-- 13. AUDITORÍA DE INVENTARIO
CREATE TABLE auditoria_stock (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_talla_id INT NOT NULL REFERENCES producto_tallas(id) ON DELETE CASCADE,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,                 
    tipo_movimiento VARCHAR(20) NOT NULL CHECK (tipo_movimiento IN ('Ingreso', 'Salida')),
    cantidad INT NOT NULL,                   
    stock_previo INT NOT NULL,               
    stock_nuevo INT NOT NULL,                
    motivo VARCHAR(255) NOT NULL,            
    requerimiento_id INT DEFAULT NULL,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 14. GESTIÓN DE REQUERIMIENTOS
CREATE TABLE requerimientos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,      
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE RESTRICT,                    
    usuario_solicitante_id INT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,     
    usuario_aprobador_id INT DEFAULT NULL REFERENCES usuarios(id) ON DELETE SET NULL,   
    tipo_solicitud VARCHAR(30) NOT NULL CHECK (tipo_solicitud IN ('Materiales_y_EPP', 'Uniformes_Almacen')),
    afecta_stock BOOLEAN NOT NULL DEFAULT FALSE, 
    estado VARCHAR(30) DEFAULT 'Borrador' CHECK (estado IN ('Borrador', 'Pendiente Aprobacion', 'Aprobado', 'Enviado', 'Entregado', 'Entregado Incompleto', 'Rechazado')),
    motivo_rechazo TEXT DEFAULT NULL,
    notas_entrega_incompleta TEXT DEFAULT NULL,
    fecha_solicitud TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_aprobacion TIMESTAMPTZ NULL DEFAULT NULL,
    fecha_envio TIMESTAMPTZ NULL DEFAULT NULL,
    fecha_entrega TIMESTAMPTZ NULL DEFAULT NULL,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 15. DETALLE DEL PEDIDO (LÍNEA POR LÍNEA)
CREATE TABLE requerimiento_detalles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requerimiento_id INT NOT NULL REFERENCES requerimientos(id) ON DELETE CASCADE,
    producto_id INT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
    producto_talla_id INT DEFAULT NULL REFERENCES producto_tallas(id) ON DELETE RESTRICT,      
    vinculo_laboral_id INT DEFAULT NULL REFERENCES vinculos_laborales(id) ON DELETE RESTRICT,     
    cantidad_solicitada INT NOT NULL,
    cantidad_aprobada INT DEFAULT 0,
    cantidad_entregada INT DEFAULT 0,        
    motivo_modificacion VARCHAR(255) DEFAULT NULL
);

ALTER TABLE personas 
ADD COLUMN fecha_ingreso DATE,
ADD COLUMN fecha_primer_contrato DATE;

-- 1. Vincular los colaboradores con su solicitud original de la pizarra
ALTER TABLE vinculos_laborales ADD COLUMN solicitud_id INT DEFAULT NULL;
ALTER TABLE vinculos_laborales ADD CONSTRAINT fk_vinculo_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitudes_personal(id) ON DELETE SET NULL;
-- 2. Restricción única de un solo vínculo activo por colaborador y empresa
CREATE UNIQUE INDEX unique_active_vinculo_per_empresa 
ON vinculos_laborales (persona_id, empresa_interna_id) 
WHERE (estado = 'Activo');


-- 1. Agregar columna de observaciones a los detalles del requerimiento (para marca, color, aroma, etc.)
ALTER TABLE requerimiento_detalles 
ADD COLUMN IF NOT EXISTS observacion TEXT;
-- 2. Agregar columna de apoyo extraordinario a la cabecera del requerimiento
ALTER TABLE requerimientos 
ADD COLUMN IF NOT EXISTS apoyo_extraordinario BOOLEAN DEFAULT FALSE;

ALTER TABLE clientes DROP CONSTRAINT IF EXISTS clientes_ruc_key;

ALTER TABLE clientes ADD CONSTRAINT uq_cliente_ruc_empresa UNIQUE (ruc, empresa_interna_id);




-- 1. Eliminar la restricción de unicidad del RUC actual si existiese por defecto
ALTER TABLE clientes DROP CONSTRAINT IF EXISTS clientes_ruc_key;
-- 2. Eliminar la restricción actual 'uq_cliente_ruc_empresa'
ALTER TABLE clientes DROP CONSTRAINT IF EXISTS uq_cliente_ruc_empresa;
-- 3. Crear una nueva restricción única compuesta (RUC + Empresa Interna)
ALTER TABLE clientes ADD CONSTRAINT uq_cliente_ruc_empresa UNIQUE (ruc, empresa_interna_id);


-- 1. Agregar columnas para la gestión de excepciones en vinculos_laborales
ALTER TABLE vinculos_laborales ADD COLUMN IF NOT EXISTS excepcion_sede BOOLEAN DEFAULT FALSE;
ALTER TABLE vinculos_laborales ADD COLUMN IF NOT EXISTS excepcion_aprobada BOOLEAN DEFAULT FALSE;

ALTER TABLE empresas_internas ADD COLUMN logo_url TEXT DEFAULT NULL;

ALTER TABLE vinculos_laborales ADD COLUMN bono DECIMAL(10, 2) DEFAULT 0.00;

ALTER TABLE vinculos_laborales ADD COLUMN vencimiento_asignacion_familiar DATE DEFAULT NULL;

-- Crear tabla de parámetros globales
CREATE TABLE parametros_sistema (
    clave VARCHAR(100) PRIMARY KEY,
    valor TEXT NOT NULL,
    descripcion VARCHAR(255),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE vacaciones_historico 
ADD COLUMN periodo_inicio DATE,
ADD COLUMN periodo_fin DATE;


-- Insertar clave de aprobación por defecto
INSERT INTO parametros_sistema (clave, valor, descripcion) 
VALUES ('clave_aprobacion_rrhh', '123456', 'Clave requerida para autorizar eliminación de personal y otras acciones críticas.');

--******************************************************************************************************************--

-- Módulo de tareo por sedes. Ejecutar en Supabase SQL Editor o con Supabase CLI.

alter table public.usuarios add column if not exists auth_user_id uuid unique references auth.users(id) on delete set null;
update public.usuarios u set auth_user_id = au.id from auth.users au
where u.auth_user_id is null and lower(u.correo) = lower(au.email);

insert into public.roles (codigo,nombre,descripcion)
select 'planilla','Planilla','Revisa, aprueba y cierra tareos mensuales.'
where not exists (select 1 from public.roles where codigo='planilla');

create table if not exists public.tipos_marcacion (
  id bigint generated by default as identity primary key, codigo varchar(20) not null unique,
  nombre varchar(120) not null, clase varchar(20) not null check (clase in ('HORAS','NOVEDAD')),
  activo boolean not null default true, es_legacy boolean not null default false, creado_en timestamptz not null default now()
);

insert into public.tipos_marcacion(codigo,nombre,clase,es_legacy) values
('HORAS','Horas trabajadas','HORAS',false),('D','Descanso laboral','NOVEDAD',false),('DFE','Descanso por feriado','NOVEDAD',false),('FI','Falta injustificada','NOVEDAD',false),('FJ','Falta justificada','NOVEDAD',false),('P','Permiso solicitado anticipadamente','NOVEDAD',false),('PSG','Permiso sin goce','NOVEDAD',false),('PCG','Permiso con goce','NOVEDAD',false),('DM','Descanso médico','NOVEDAD',false),('L','Licencia','NOVEDAD',false),('V','Vacaciones','NOVEDAD',false),('R','Renuncia o retiro','NOVEDAD',false),('.--','No programado','NOVEDAD',false),('PG','Permiso con goce (legado)','NOVEDAD',true),('S','Suspendido (legado)','NOVEDAD',true),('TS','Trabajador suspendido (legado)','NOVEDAD',true),('TC','Término de contrato (legado)','NOVEDAD',true),('CPP','Cancelación periodo prueba (legado)','NOVEDAD',true),('Ab','Abandono de trabajo (legado)','NOVEDAD',true),('Base','Retén base (legado)','NOVEDAD',true)
on conflict(codigo) do update set nombre=excluded.nombre,clase=excluded.clase,es_legacy=excluded.es_legacy;

create table if not exists public.tareo_configuracion (
 id bigint generated by default as identity primary key, empresa_interna_id int references public.empresas_internas(id) on delete cascade,
 limite_horas_diarias numeric(5,2) not null default 16 check(limite_horas_diarias between 1 and 24),
 limite_jornada_inusual numeric(5,2) not null default 12 check(limite_jornada_inusual between 1 and 24), unique nulls not distinct(empresa_interna_id)
);

create table if not exists public.tareo_periodos (
 id bigint generated by default as identity primary key, sede_id int not null references public.sedes(id) on delete restrict,
 mes smallint not null check(mes between 1 and 12), anio smallint not null check(anio between 2020 and 2100),
 supervisor_responsable_id int not null references public.usuarios(id) on delete restrict,
 estado varchar(20) not null default 'Borrador' check(estado in ('Borrador','Enviado','Observado','Corregido','Aprobado','Cerrado')),
 observaciones text, enviado_en timestamptz, enviado_por_id int references public.usuarios(id), aprobado_en timestamptz, aprobado_por_id int references public.usuarios(id), cerrado_en timestamptz, cerrado_por_id int references public.usuarios(id), creado_en timestamptz not null default now(), actualizado_en timestamptz not null default now(), unique(sede_id,mes,anio)
);

create table if not exists public.tareo_marcaciones (
 id bigint generated by default as identity primary key, periodo_id bigint not null references public.tareo_periodos(id) on delete cascade,
 vinculo_laboral_id int not null references public.vinculos_laborales(id) on delete restrict, fecha date not null,
 sede_trabajada_id int not null references public.sedes(id) on delete restrict, cliente_id int not null references public.clientes(id) on delete restrict,
 supervisor_registro_id int not null references public.usuarios(id), tipo_marcacion_id bigint not null references public.tipos_marcacion(id), horas numeric(5,2) not null default 0 check(horas between 0 and 24),
 es_cobertura boolean not null default false, vinculo_cubierto_id int references public.vinculos_laborales(id) on delete set null, motivo_cobertura text, observacion text, alertas jsonb not null default '[]'::jsonb,
 creado_en timestamptz not null default now(), creado_por_id int not null references public.usuarios(id), actualizado_en timestamptz not null default now(), actualizado_por_id int not null references public.usuarios(id),
 check((es_cobertura and nullif(trim(coalesce(motivo_cobertura,'')),'') is not null) or not es_cobertura)
);

create unique index if not exists tareo_marcaciones_duplicado_exacto on public.tareo_marcaciones(periodo_id,vinculo_laboral_id,fecha,sede_trabajada_id,tipo_marcacion_id,horas,coalesce(vinculo_cubierto_id,-1),coalesce(motivo_cobertura,''));
create index if not exists tareo_marcaciones_fecha_idx on public.tareo_marcaciones(periodo_id,fecha,vinculo_laboral_id);
create table if not exists public.tareo_auditoria (
 id bigint generated by default as identity primary key, periodo_id bigint not null references public.tareo_periodos(id) on delete cascade, marcacion_id bigint references public.tareo_marcaciones(id) on delete set null,
 accion varchar(30) not null, valor_anterior jsonb, valor_nuevo jsonb, usuario_id int references public.usuarios(id) on delete set null, motivo text, estado_periodo varchar(20), creado_en timestamptz not null default now()
);

create or replace function public.tareo_usuario_actual_id() returns int language sql stable security definer set search_path=public as $$ select id from public.usuarios where activo and (auth_user_id=auth.uid() or lower(correo)=lower(coalesce(auth.jwt()->>'email',''))) limit 1 $$;
create or replace function public.tareo_rol_actual() returns text language sql stable security definer set search_path=public as $$ select r.codigo from public.usuarios u join public.roles r on r.id=u.rol_id where u.id=public.tareo_usuario_actual_id() $$;
create or replace function public.tareo_es_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.tareo_rol_actual() in ('admin','gerencia'),false) $$;
create or replace function public.tareo_puede_operar_sede(p_sede_id int) returns boolean language sql stable security definer set search_path=public as $$ select public.tareo_es_admin() or exists(select 1 from public.usuario_sedes where usuario_id=public.tareo_usuario_actual_id() and sede_id=p_sede_id) $$;

create or replace function public.tareo_validar_marcacion() returns trigger language plpgsql security definer set search_path=public as $$
declare p public.tareo_periodos; v public.vinculos_laborales; clase text; total_horas numeric; avisos jsonb:='[]'::jsonb;
begin
 select * into p from public.tareo_periodos where id=new.periodo_id; if p is null then raise exception 'Periodo no encontrado'; end if;
 if new.fecha < make_date(p.anio,p.mes,1) or new.fecha > (make_date(p.anio,p.mes,1)+interval '1 month - 1 day')::date then raise exception 'La fecha no pertenece al periodo'; end if;
 if p.estado not in ('Borrador','Observado','Corregido') then raise exception 'El periodo está bloqueado'; end if;
 if new.sede_trabajada_id<>p.sede_id or not public.tareo_puede_operar_sede(new.sede_trabajada_id) then raise exception 'No tiene acceso a la sede trabajada'; end if;
 select * into v from public.vinculos_laborales where id=new.vinculo_laboral_id; if v.fecha_cese is not null and new.fecha>v.fecha_cese then raise exception 'No se permiten horas posteriores al cese'; end if;
 select clase into clase from public.tipos_marcacion where id=new.tipo_marcacion_id and activo; if clase is null or ((clase='HORAS')<>(new.horas>0)) then raise exception 'Tipo u horas de marcación inválidos'; end if;
 if exists(select 1 from public.vacaciones_historico where vinculo_laboral_id=new.vinculo_laboral_id and new.fecha between fecha_inicio and fecha_fin) and new.horas>0 then avisos:=avisos||jsonb_build_array('Horas registradas durante vacaciones'); end if;
 select coalesce(sum(horas),0) into total_horas from public.tareo_marcaciones where vinculo_laboral_id=new.vinculo_laboral_id and fecha=new.fecha and id is distinct from new.id; if total_horas+new.horas>16 then avisos:=avisos||jsonb_build_array('Jornada diaria inusual'); end if;
 new.cliente_id:=(select cliente_id from public.sedes where id=new.sede_trabajada_id); new.supervisor_registro_id:=public.tareo_usuario_actual_id(); new.actualizado_por_id:=public.tareo_usuario_actual_id(); new.actualizado_en:=now(); new.alertas:=avisos;
 if tg_op='INSERT' then new.creado_por_id:=public.tareo_usuario_actual_id(); new.creado_en:=now(); end if; return new;
end $$;
drop trigger if exists trg_tareo_validar_marcacion on public.tareo_marcaciones;
create trigger trg_tareo_validar_marcacion before insert or update on public.tareo_marcaciones for each row execute function public.tareo_validar_marcacion();

create or replace function public.tareo_auditar_marcacion() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.tareo_auditoria(periodo_id,marcacion_id,accion,valor_anterior,valor_nuevo,usuario_id,estado_periodo) values(coalesce(new.periodo_id,old.periodo_id),coalesce(new.id,old.id),tg_op,to_jsonb(old),to_jsonb(new),public.tareo_usuario_actual_id(),(select estado from public.tareo_periodos where id=coalesce(new.periodo_id,old.periodo_id))); return coalesce(new,old); end $$;
drop trigger if exists trg_tareo_auditar_marcacion on public.tareo_marcaciones;
create trigger trg_tareo_auditar_marcacion after insert or update or delete on public.tareo_marcaciones for each row execute function public.tareo_auditar_marcacion();

create or replace function public.tareo_cambiar_estado(p_periodo_id bigint,p_accion text,p_observacion text default null,p_motivo text default null) returns public.tareo_periodos language plpgsql security definer set search_path=public as $$
declare p public.tareo_periodos; u int:=public.tareo_usuario_actual_id(); rol text:=public.tareo_rol_actual(); siguiente text;
begin select * into p from public.tareo_periodos where id=p_periodo_id for update; if p is null then raise exception 'Periodo no encontrado'; end if;
 siguiente:=case p_accion when 'enviar' then case when p.estado='Borrador' then 'Enviado' when p.estado='Observado' then 'Corregido' when p.estado='Corregido' then 'Enviado' end when 'observar' then case when p.estado in ('Enviado','Corregido') and rol in ('planilla','admin') then 'Observado' end when 'aprobar' then case when p.estado in ('Enviado','Corregido') and rol in ('planilla','admin') then 'Aprobado' end when 'cerrar' then case when p.estado='Aprobado' and rol in ('planilla','admin') then 'Cerrado' end when 'reabrir' then case when p.estado in ('Aprobado','Cerrado') and rol='admin' then 'Borrador' end end;
 if siguiente is null then raise exception 'Transición no permitida'; end if; if p_accion='reabrir' and nullif(trim(coalesce(p_motivo,'')),'') is null then raise exception 'La reapertura requiere motivo'; end if;
 update public.tareo_periodos set estado=siguiente,observaciones=coalesce(p_observacion,observaciones),enviado_en=case when siguiente='Enviado' then now() else enviado_en end,enviado_por_id=case when siguiente='Enviado' then u else enviado_por_id end,aprobado_en=case when siguiente='Aprobado' then now() else aprobado_en end,aprobado_por_id=case when siguiente='Aprobado' then u else aprobado_por_id end,cerrado_en=case when siguiente='Cerrado' then now() else cerrado_en end,cerrado_por_id=case when siguiente='Cerrado' then u else cerrado_por_id end,actualizado_en=now() where id=p_periodo_id returning * into p;
 insert into public.tareo_auditoria(periodo_id,accion,usuario_id,motivo,estado_periodo) values(p.id,upper(p_accion),u,coalesce(p_motivo,p_observacion),p.estado); return p;
end $$;

create or replace view public.v_tareo_consolidado as
select tm.periodo_id,tp.anio,tp.mes,tm.vinculo_laboral_id,vl.persona_id,tm.sede_trabajada_id,tm.cliente_id,sum(tm.horas) total_horas,count(distinct tm.fecha) filter(where tm.horas>0) dias_laborados,count(*) filter(where t.codigo='D') descansos,count(*) filter(where t.codigo='DFE') descansos_feriado,count(*) filter(where t.codigo='FI') faltas_injustificadas,count(*) filter(where t.codigo='FJ') faltas_justificadas,count(*) filter(where t.codigo in ('P','PSG','PCG','PG')) permisos,count(*) filter(where t.codigo='DM') descansos_medicos,count(*) filter(where t.codigo='V') vacaciones,count(*) filter(where t.codigo='R') retiros,count(*) filter(where t.codigo='.--') no_programados,sum(tm.horas) filter(where tm.es_cobertura) horas_cobertura
from public.tareo_marcaciones tm join public.tareo_periodos tp on tp.id=tm.periodo_id join public.vinculos_laborales vl on vl.id=tm.vinculo_laboral_id join public.tipos_marcacion t on t.id=tm.tipo_marcacion_id
group by tm.periodo_id,tp.anio,tp.mes,tm.vinculo_laboral_id,vl.persona_id,tm.sede_trabajada_id,tm.cliente_id;

alter table public.tareo_periodos enable row level security; alter table public.tareo_marcaciones enable row level security; alter table public.tareo_auditoria enable row level security; alter table public.tipos_marcacion enable row level security; alter table public.tareo_configuracion enable row level security;
create policy "tareo_periodos_select" on public.tareo_periodos for select using(public.tareo_es_admin() or public.tareo_rol_actual()='planilla' or public.tareo_puede_operar_sede(sede_id));
create policy "tareo_periodos_insert" on public.tareo_periodos for insert with check(public.tareo_puede_operar_sede(sede_id) and supervisor_responsable_id=public.tareo_usuario_actual_id());
create policy "tareo_periodos_update" on public.tareo_periodos for update using(public.tareo_es_admin() or (public.tareo_puede_operar_sede(sede_id) and supervisor_responsable_id=public.tareo_usuario_actual_id() and estado in ('Borrador','Observado','Corregido')));
create policy "tareo_marcaciones_access" on public.tareo_marcaciones for all using(exists(select 1 from public.tareo_periodos p where p.id=periodo_id and (public.tareo_es_admin() or public.tareo_rol_actual()='planilla' or public.tareo_puede_operar_sede(p.sede_id)))) with check(public.tareo_puede_operar_sede(sede_trabajada_id));
create policy "tareo_catalogos_select" on public.tipos_marcacion for select using(true);
create policy "tareo_config_select" on public.tareo_configuracion for select using(public.tareo_es_admin() or public.tareo_rol_actual()='planilla');
create policy "tareo_auditoria_select" on public.tareo_auditoria for select using(public.tareo_es_admin() or public.tareo_rol_actual()='planilla' or exists(select 1 from public.tareo_periodos p where p.id=periodo_id and public.tareo_puede_operar_sede(p.sede_id)));

********************************************************************************************************************************************************************************

-- Corrección para instalaciones que ya ejecutaron la primera migración.
create or replace function public.tareo_validar_marcacion() returns trigger language plpgsql security definer set search_path=public as $$
declare p public.tareo_periodos; v public.vinculos_laborales; v_clase text; total_horas numeric; avisos jsonb:='[]'::jsonb;
begin
 select * into p from public.tareo_periodos where id=new.periodo_id; if p is null then raise exception 'Periodo no encontrado'; end if;
 if new.fecha < make_date(p.anio,p.mes,1) or new.fecha > (make_date(p.anio,p.mes,1)+interval '1 month - 1 day')::date then raise exception 'La fecha no pertenece al periodo'; end if;
 if p.estado not in ('Borrador','Observado','Corregido') then raise exception 'El periodo está bloqueado'; end if;
 if new.sede_trabajada_id<>p.sede_id or not public.tareo_puede_operar_sede(new.sede_trabajada_id) then raise exception 'No tiene acceso a la sede trabajada'; end if;
 select * into v from public.vinculos_laborales where id=new.vinculo_laboral_id; if v.fecha_cese is not null and new.fecha>v.fecha_cese then raise exception 'No se permiten horas posteriores al cese'; end if;
 select tm.clase into v_clase from public.tipos_marcacion tm where tm.id=new.tipo_marcacion_id and tm.activo;
 if v_clase is null or ((v_clase='HORAS')<>(new.horas>0)) then raise exception 'Tipo u horas de marcación inválidos'; end if;
 if exists(select 1 from public.vacaciones_historico where vinculo_laboral_id=new.vinculo_laboral_id and new.fecha between fecha_inicio and fecha_fin) and new.horas>0 then avisos:=avisos||jsonb_build_array('Horas registradas durante vacaciones'); end if;
 select coalesce(sum(horas),0) into total_horas from public.tareo_marcaciones where vinculo_laboral_id=new.vinculo_laboral_id and fecha=new.fecha and id is distinct from new.id;
 if total_horas+new.horas>16 then avisos:=avisos||jsonb_build_array('Jornada diaria inusual'); end if;
 new.cliente_id:=(select cliente_id from public.sedes where id=new.sede_trabajada_id); new.supervisor_registro_id:=public.tareo_usuario_actual_id(); new.actualizado_por_id:=public.tareo_usuario_actual_id(); new.actualizado_en:=now(); new.alertas:=avisos;
 if tg_op='INSERT' then new.creado_por_id:=public.tareo_usuario_actual_id(); new.creado_en:=now(); end if; return new;
end $$;