-- 1. Tabla de Roles
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE, 
    nombre VARCHAR(50) NOT NULL,        
    descripcion TEXT
);

-- 2. Empresas Internas
CREATE TABLE empresas_internas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL, 
    representante_legal VARCHAR(150),       
    direccion_fiscal VARCHAR(255),          
    activo BOOLEAN DEFAULT TRUE
);

-- 3. Clientes
CREATE TABLE clientes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_interna_id INT NOT NULL REFERENCES empresas_internas(id) ON DELETE RESTRICT,     
    ruc VARCHAR(11) NOT NULL UNIQUE,     
    razon_social VARCHAR(150) NOT NULL,  
    activo BOOLEAN DEFAULT TRUE
);

-- 4. Sedes Operativas
CREATE TABLE sedes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,                 
    nombre VARCHAR(150) NOT NULL,            
    direccion VARCHAR(255),                  
    distrito VARCHAR(100),                   
    contacto_nombre VARCHAR(100),            
    contacto_telefono VARCHAR(20),           
    presupuesto DECIMAL(10, 2) DEFAULT 0.00, 
    activo BOOLEAN DEFAULT TRUE
);

-- 5. Usuarios del Sistema
CREATE TABLE usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL, 
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(150) UNIQUE,
    rol_id INT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    activo BOOLEAN DEFAULT TRUE
);

-- 6. Matriz de Asignación (Supervisores a Sedes)
CREATE TABLE usuario_sedes (
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, sede_id)
);

-- 7. DICCIONARIOS DE DATOS (CATÁLOGOS)
CREATE TABLE cargos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE tipos_documento (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE, 
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE tipos_trabajador (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE bancos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE sistemas_pension (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE, 
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('ONP', 'AFP'))
);

CREATE TABLE regimenes_laborales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE, 
    dias_vacaciones INT NOT NULL        
);

CREATE TABLE modalidades_contrato (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE 
);

-- Ubigeo en formato plano
CREATE TABLE ubigeo_distritos (
    id CHAR(6) PRIMARY KEY,             
    departamento VARCHAR(50) NOT NULL,  
    provincia VARCHAR(50) NOT NULL,     
    distrito VARCHAR(50) NOT NULL       
);

-- 8. GESTIÓN DE PERSONAL
-- 8.1 Ficha Maestra Única (La Persona)
CREATE TABLE personas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento_id INT NOT NULL REFERENCES tipos_documento(id) ON DELETE RESTRICT,
    numero_documento VARCHAR(20) NOT NULL UNIQUE, 
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    sexo VARCHAR(20) NOT NULL CHECK (sexo IN ('Masculino', 'Femenino')),
    fecha_nacimiento DATE NOT NULL,
    direccion VARCHAR(255),
    ubigeo_id CHAR(6) REFERENCES ubigeo_distritos(id) ON DELETE RESTRICT,                     
    telefono VARCHAR(20),
    correo VARCHAR(150),
    
    banco_sueldo_id INT REFERENCES bancos(id) ON DELETE SET NULL,
    cuenta_sueldo VARCHAR(50),
    banco_cts_id INT REFERENCES bancos(id) ON DELETE SET NULL,
    cuenta_cts VARCHAR(50),
    sistema_pension_id INT NOT NULL REFERENCES sistemas_pension(id) ON DELETE RESTRICT,
    codigo_cuss_afp VARCHAR(20),
    
    fecha_ultimo_emo DATE,
    talla_polo VARCHAR(10),
    talla_pantalon VARCHAR(10),
    talla_calzado VARCHAR(10),
    
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 8.2 El Puesto Dinámico (Vínculo Laboral)
CREATE TABLE vinculos_laborales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id INT NOT NULL REFERENCES personas(id) ON DELETE CASCADE,               
    empresa_interna_id INT NOT NULL REFERENCES empresas_internas(id) ON DELETE RESTRICT,       
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE RESTRICT,                  
    cargo_id INT NOT NULL REFERENCES cargos(id) ON DELETE RESTRICT,
    tipo_trabajador_id INT NOT NULL REFERENCES tipos_trabajador(id) ON DELETE RESTRICT,
    lugar_especifico_trabajo VARCHAR(150),
    
    regimen_laboral_id INT NOT NULL REFERENCES regimenes_laborales(id) ON DELETE RESTRICT,
    asignacion_familiar BOOLEAN DEFAULT FALSE,
    sueldo_basico DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    fecha_cese DATE DEFAULT NULL,
    motivo_cese TEXT DEFAULT NULL,
    
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. HISTORIALES Y CONTROL LEGAL
-- 9.1 Historial de Contratos
CREATE TABLE contratos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinculo_laboral_id INT NOT NULL REFERENCES vinculos_laborales(id) ON DELETE CASCADE,
    modalidad_contrato_id INT NOT NULL REFERENCES modalidades_contrato(id) ON DELETE RESTRICT,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE, 
    estado VARCHAR(20) DEFAULT 'Vigente' CHECK (estado IN ('Vigente', 'Vencido', 'Renovado', 'Anulado')),
    archivo_pdf VARCHAR(255), 
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9.2 Control Histórico de Vacaciones
CREATE TABLE vacaciones_historico (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinculo_laboral_id INT NOT NULL REFERENCES vinculos_laborales(id) ON DELETE CASCADE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    dias_calendario INT NOT NULL, 
    notas TEXT,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 10. PIZARRA DIGITAL DE RECLUTAMIENTO
CREATE TABLE solicitudes_personal (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE RESTRICT,
    cargo_id INT NOT NULL REFERENCES cargos(id) ON DELETE RESTRICT,
    turno VARCHAR(50) NOT NULL,
    genero_requerido VARCHAR(20) DEFAULT 'Indistinto' CHECK (genero_requerido IN ('Masculino', 'Femenino', 'Indistinto', 'Mixto')),
    motivo_vacante TEXT,
    plazas_solicitadas INT NOT NULL DEFAULT 1,
    plazas_cubiertas INT NOT NULL DEFAULT 0,
    estado VARCHAR(20) DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Parcial', 'Completado')),
    fecha_solicitud DATE NOT NULL,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 11. DICCIONARIOS LOGÍSTICOS
CREATE TABLE categorias_producto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE, 
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE unidades_medida (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,  
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE proveedores (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    contacto_nombre VARCHAR(100),
    contacto_telefono VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tallas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor VARCHAR(10) NOT NULL UNIQUE,   
    activo BOOLEAN DEFAULT TRUE
);

-- 12. CATÁLOGO CENTRAL Y VARIANTES
CREATE TABLE productos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) UNIQUE,                  
    categoria_id INT NOT NULL REFERENCES categorias_producto(id) ON DELETE RESTRICT,
    unidad_medida_id INT NOT NULL REFERENCES unidades_medida(id) ON DELETE RESTRICT,
    proveedor_id INT REFERENCES proveedores(id) ON DELETE SET NULL,                        
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio_unitario DECIMAL(10, 2) DEFAULT 0.00,
    es_uniforme BOOLEAN DEFAULT FALSE,       
    activo BOOLEAN DEFAULT TRUE,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE producto_tallas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id INT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    talla_id INT NOT NULL REFERENCES tallas(id) ON DELETE RESTRICT,                   
    stock_actual INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_producto_talla UNIQUE (producto_id, talla_id) 
);

-- 13. AUDITORÍA DE INVENTARIO
CREATE TABLE auditoria_stock (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_talla_id INT NOT NULL REFERENCES producto_tallas(id) ON DELETE CASCADE,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,                 
    tipo_movimiento VARCHAR(20) NOT NULL CHECK (tipo_movimiento IN ('Ingreso', 'Salida')),
    cantidad INT NOT NULL,                   
    stock_previo INT NOT NULL,               
    stock_nuevo INT NOT NULL,                
    motivo VARCHAR(255) NOT NULL,            
    requerimiento_id INT DEFAULT NULL,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 14. GESTIÓN DE REQUERIMIENTOS
CREATE TABLE requerimientos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,      
    sede_id INT NOT NULL REFERENCES sedes(id) ON DELETE RESTRICT,                    
    usuario_solicitante_id INT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,     
    usuario_aprobador_id INT DEFAULT NULL REFERENCES usuarios(id) ON DELETE SET NULL,   
    tipo_solicitud VARCHAR(30) NOT NULL CHECK (tipo_solicitud IN ('Materiales_y_EPP', 'Uniformes_Almacen')),
    afecta_stock BOOLEAN NOT NULL DEFAULT FALSE, 
    estado VARCHAR(30) DEFAULT 'Borrador' CHECK (estado IN ('Borrador', 'Pendiente Aprobacion', 'Aprobado', 'Enviado', 'Entregado', 'Entregado Incompleto', 'Rechazado')),
    motivo_rechazo TEXT DEFAULT NULL,
    notas_entrega_incompleta TEXT DEFAULT NULL,
    fecha_solicitud TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_aprobacion TIMESTAMPTZ NULL DEFAULT NULL,
    fecha_envio TIMESTAMPTZ NULL DEFAULT NULL,
    fecha_entrega TIMESTAMPTZ NULL DEFAULT NULL,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 15. DETALLE DEL PEDIDO (LÍNEA POR LÍNEA)
CREATE TABLE requerimiento_detalles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requerimiento_id INT NOT NULL REFERENCES requerimientos(id) ON DELETE CASCADE,
    producto_id INT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
    producto_talla_id INT DEFAULT NULL REFERENCES producto_tallas(id) ON DELETE RESTRICT,      
    vinculo_laboral_id INT DEFAULT NULL REFERENCES vinculos_laborales(id) ON DELETE RESTRICT,     
    cantidad_solicitada INT NOT NULL,
    cantidad_aprobada INT DEFAULT 0,
    cantidad_entregada INT DEFAULT 0,        
    motivo_modificacion VARCHAR(255) DEFAULT NULL
);

ALTER TABLE personas 
ADD COLUMN fecha_ingreso DATE,
ADD COLUMN fecha_primer_contrato DATE;

-- 1. Vincular los colaboradores con su solicitud original de la pizarra
ALTER TABLE vinculos_laborales ADD COLUMN solicitud_id INT DEFAULT NULL;
ALTER TABLE vinculos_laborales ADD CONSTRAINT fk_vinculo_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitudes_personal(id) ON DELETE SET NULL;
-- 2. Restricción única de un solo vínculo activo por colaborador y empresa
CREATE UNIQUE INDEX unique_active_vinculo_per_empresa 
ON vinculos_laborales (persona_id, empresa_interna_id) 
WHERE (estado = 'Activo');


-- 1. Agregar columna de observaciones a los detalles del requerimiento (para marca, color, aroma, etc.)
ALTER TABLE requerimiento_detalles 
ADD COLUMN IF NOT EXISTS observacion TEXT;
-- 2. Agregar columna de apoyo extraordinario a la cabecera del requerimiento
ALTER TABLE requerimientos 
ADD COLUMN IF NOT EXISTS apoyo_extraordinario BOOLEAN DEFAULT FALSE;

ALTER TABLE clientes DROP CONSTRAINT IF EXISTS clientes_ruc_key;

ALTER TABLE clientes ADD CONSTRAINT uq_cliente_ruc_empresa UNIQUE (ruc, empresa_interna_id);




-- 1. Eliminar la restricción de unicidad del RUC actual si existiese por defecto
ALTER TABLE clientes DROP CONSTRAINT IF EXISTS clientes_ruc_key;
-- 2. Eliminar la restricción actual 'uq_cliente_ruc_empresa'
ALTER TABLE clientes DROP CONSTRAINT IF EXISTS uq_cliente_ruc_empresa;
-- 3. Crear una nueva restricción única compuesta (RUC + Empresa Interna)
ALTER TABLE clientes ADD CONSTRAINT uq_cliente_ruc_empresa UNIQUE (ruc, empresa_interna_id);


-- 1. Agregar columnas para la gestión de excepciones en vinculos_laborales
ALTER TABLE vinculos_laborales ADD COLUMN IF NOT EXISTS excepcion_sede BOOLEAN DEFAULT FALSE;
ALTER TABLE vinculos_laborales ADD COLUMN IF NOT EXISTS excepcion_aprobada BOOLEAN DEFAULT FALSE;

ALTER TABLE empresas_internas ADD COLUMN logo_url TEXT DEFAULT NULL;

ALTER TABLE vinculos_laborales ADD COLUMN bono DECIMAL(10, 2) DEFAULT 0.00;

ALTER TABLE vinculos_laborales ADD COLUMN vencimiento_asignacion_familiar DATE DEFAULT NULL;

-- Crear tabla de parámetros globales
CREATE TABLE parametros_sistema (
    clave VARCHAR(100) PRIMARY KEY,
    valor TEXT NOT NULL,
    descripcion VARCHAR(255),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE vacaciones_historico 
ADD COLUMN periodo_inicio DATE,
ADD COLUMN periodo_fin DATE;


-- Insertar clave de aprobación por defecto
INSERT INTO parametros_sistema (clave, valor, descripcion) 
VALUES ('clave_aprobacion_rrhh', '123456', 'Clave requerida para autorizar eliminación de personal y otras acciones críticas.');