import React, { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, Download, FileSpreadsheet, Plus, RefreshCw, Send, X } from "lucide-react";
import * as XLSX from "xlsx";
import { supabase } from "../utils/supabase";
import { useAuth } from "../utils/authContext";

type Periodo = { id:number; sede_id:number; mes:number; anio:number; estado:string; observaciones?:string; sedes?:any; supervisor_responsable_id:number };
const meses = ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const diasEnMes = (m:number,a:number) => new Date(a,m,0).getDate();
const fmt = (n:number) => String(n).padStart(2,"0");

export function TareoSedes() {
  const { user, role } = useAuth();
  const hoy = new Date();
  const [sedes,setSedes] = useState<any[]>([]); const [tipos,setTipos] = useState<any[]>([]); const [periodos,setPeriodos] = useState<Periodo[]>([]);
  const [periodo,setPeriodo] = useState<Periodo|null>(null); const [marcaciones,setMarcaciones] = useState<any[]>([]); const [personal,setPersonal] = useState<any[]>([]);
  const [mes,setMes] = useState(hoy.getMonth()+1); const [anio,setAnio] = useState(hoy.getFullYear()); const [clienteId,setClienteId] = useState(""); const [sedeId,setSedeId] = useState("");
  const [vistaCliente,setVistaCliente] = useState(false); const [personalCliente,setPersonalCliente] = useState<any[]>([]);
  const [periodosCliente,setPeriodosCliente] = useState<Periodo[]>([]); const [marcacionesCliente,setMarcacionesCliente] = useState<any[]>([]);
  const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [modal,setModal] = useState<any>(null); const [form,setForm] = useState<any>({tipo:"HORAS",horas:8,es_cobertura:false,motivo_cobertura:"",observacion:"",vinculo_cubierto_id:""});
  const [coberturaPicker,setCoberturaPicker] = useState(false); const [candidatosCobertura,setCandidatosCobertura] = useState<any[]>([]); const [coberturaVinculoId,setCoberturaVinculoId] = useState(""); const [coberturaFecha,setCoberturaFecha] = useState(""); const [busquedaCobertura,setBusquedaCobertura] = useState("");
  const esPlanilla = role === "planilla" || role === "admin"; const puedeEditarPeriodo = (p:Periodo|null) => !!p && ["Borrador","Observado","Corregido"].includes(p.estado) && (role === "supervisor" || role === "admin"); const editable = puedeEditarPeriodo(periodo);

  const cargarBase = async () => { setLoading(true); setError(""); try {
    let sedesPermitidas:number[]|null=null;
    if(role==="supervisor" && user){ const {data:asignaciones,error:asignacionesError}=await supabase.from("usuario_sedes").select("sede_id").eq("usuario_id",user.id); if(asignacionesError) throw asignacionesError; sedesPermitidas=(asignaciones||[]).map(a=>a.sede_id); }
    let consultaSedes=supabase.from("sedes").select("id,nombre,cliente_id,clientes(razon_social,empresa_interna_id)").eq("activo",true).order("nombre");
    if(sedesPermitidas!==null) consultaSedes=sedesPermitidas.length ? consultaSedes.in("id",sedesPermitidas) : consultaSedes.in("id",[-1]);
    const [s,t,p] = await Promise.all([
      consultaSedes,
      supabase.from("tipos_marcacion").select("*").eq("activo",true).order("clase").order("codigo"),
      supabase.from("tareo_periodos").select("*,sedes(id,nombre,clientes(razon_social))").order("anio",{ascending:false}).order("mes",{ascending:false})
    ]);
    if(s.error||t.error||p.error) throw s.error||t.error||p.error; setSedes(s.data||[]); setTipos(t.data||[]); setPeriodos(p.data||[]); if(role==="supervisor" && sedesPermitidas?.length===0) setError("No tiene sedes asignadas. Un administrador debe asignarle al menos una sede en Accesos y Roles.");
  } catch(e:any) { setError(e.message||"No se pudo cargar el tareo. Aplique primero la migración de Supabase."); } finally { setLoading(false); } };
  useEffect(()=>{ cargarBase(); },[]);

  const clientes = useMemo(() => Array.from(new Map<number, {id:number;nombre:string}>(sedes.map(s => [s.cliente_id, { id:s.cliente_id, nombre:s.clientes?.razon_social || "Cliente sin nombre" }])).values()).sort((a,b)=>a.nombre.localeCompare(b.nombre)), [sedes]);
  const sedesFiltradas = useMemo(() => sedes.filter(s => !clienteId || String(s.cliente_id) === clienteId), [sedes,clienteId]);

  const abrirPeriodo = async (p:Periodo) => { setVistaCliente(false); setPeriodo(p); setSedeId(String(p.sede_id)); setClienteId(String(sedes.find(s=>s.id===p.sede_id)?.cliente_id || "")); setMes(p.mes); setAnio(p.anio); setLoading(true); try {
    const [m,v] = await Promise.all([
      supabase.from("tareo_marcaciones").select("*,tipos_marcacion(codigo,nombre),vinculos_laborales!tareo_marcaciones_vinculo_laboral_id_fkey(id,persona_id,sede_id,cargos(nombre),personas(nombres,apellidos,numero_documento),sedes(nombre)),vinculo_cubierto:vinculos_laborales!tareo_marcaciones_vinculo_cubierto_id_fkey(id,personas(nombres,apellidos))").eq("periodo_id",p.id).order("fecha"),
      supabase.from("vinculos_laborales").select("id,persona_id,sede_id,fecha_ingreso,fecha_cese,cargos(nombre),personas(nombres,apellidos,numero_documento),sedes(nombre)").eq("estado","Activo").eq("sede_id",p.sede_id)
    ]); if(m.error||v.error) throw m.error||v.error; setMarcaciones(m.data||[]); setPersonal(v.data||[]);
  } catch(e:any) { setError(e.message); } finally { setLoading(false); } };

  const crearPeriodo = async () => { if(!user || !sedeId) return setError("Seleccione una sede."); setLoading(true); try {
    const {data,error:err} = await supabase.from("tareo_periodos").insert({sede_id:Number(sedeId),mes,anio,supervisor_responsable_id:user.id}).select("*,sedes(id,nombre,clientes(razon_social))").single();
    if(err) throw err; setPeriodos([data,...periodos]); await abrirPeriodo(data);
  } catch(e:any) { setError(e.message); } finally { setLoading(false); } };
  const abrirCliente = async () => { if(!clienteId || !user) return setError("Seleccione un cliente."); setLoading(true); setError(""); try {
    const sedesDelCliente=sedes.filter(s=>String(s.cliente_id)===clienteId); const encontrados:Periodo[]=[];
    for(const sede of sedesDelCliente){ let p=periodos.find(x=>x.sede_id===sede.id&&x.mes===mes&&x.anio===anio); if(!p){ const {data,error:crearError}=await supabase.from("tareo_periodos").insert({sede_id:sede.id,mes,anio,supervisor_responsable_id:user.id}).select("*,sedes(id,nombre,clientes(razon_social))").single(); if(crearError) throw crearError; p=data; } encontrados.push(p); }
    const ids=encontrados.map(p=>p.id); const [m,v]=await Promise.all([
      supabase.from("tareo_marcaciones").select("*,tipos_marcacion(codigo,nombre),vinculos_laborales!tareo_marcaciones_vinculo_laboral_id_fkey(id,persona_id,sede_id,cargos(nombre),personas(nombres,apellidos,numero_documento),sedes(nombre))").in("periodo_id",ids).order("fecha"),
      supabase.from("vinculos_laborales").select("id,persona_id,sede_id,fecha_ingreso,fecha_cese,cargos(nombre),personas(nombres,apellidos,numero_documento),sedes!inner(id,nombre,cliente_id)").eq("estado","Activo").in("sede_id",sedesDelCliente.map(s=>s.id)).order("sede_id")
    ]); if(m.error||v.error) throw m.error||v.error;
    setPeriodo(null); setMarcaciones([]); setPersonal([]); setPeriodosCliente(encontrados); setMarcacionesCliente(m.data||[]); setPersonalCliente(v.data||[]); setPeriodos(prev=>[...encontrados.filter(n=>!prev.some(x=>x.id===n.id)),...prev]); setVistaCliente(true);
  } catch(e:any) { setError(e.message); } finally { setLoading(false); } };
  const seleccionar = () => { if(clienteId && !sedeId) return abrirCliente(); const p=periodos.find(x=>x.sede_id===Number(sedeId)&&x.mes===mes&&x.anio===anio); if(p) abrirPeriodo(p); else crearPeriodo(); };
  const abrirCobertura = async () => { if(!periodo) return; setLoading(true); setError(""); try {
    const {data,error:err}=await supabase.from("vinculos_laborales").select("id,persona_id,sede_id,fecha_ingreso,fecha_cese,cargos(nombre),personas(nombres,apellidos,numero_documento),sedes(nombre)").eq("estado","Activo").order("sede_id");
    if(err) throw err; setCandidatosCobertura(data||[]); setCoberturaVinculoId(""); setCoberturaFecha(`${anio}-${fmt(mes)}-01`); setBusquedaCobertura(""); setCoberturaPicker(true);
  } catch(e:any) { setError(e.message); } finally { setLoading(false); } };
  const iniciarCobertura = () => { const candidato=candidatosCobertura.find(v=>v.id===Number(coberturaVinculoId)); if(!candidato || !coberturaFecha) return setError("Seleccione trabajador y fecha de cobertura."); setCoberturaPicker(false); setModal({...candidato,fecha:coberturaFecha}); setForm({tipo:"HORAS",horas:8,es_cobertura:true,motivo_cobertura:"",observacion:"",vinculo_cubierto_id:""}); };
  const guardar = async () => { const periodoObjetivo:Periodo|null=modal?.periodo||periodo; if(!modal||!periodoObjetivo||!user) return; const tipo=tipos.find(t=>t.codigo===form.tipo); if(!tipo) return; setLoading(true); try {
    const payload={periodo_id:periodoObjetivo.id,vinculo_laboral_id:modal.id,fecha:modal.fecha,sede_trabajada_id:periodoObjetivo.sede_id,cliente_id:periodoObjetivo.sedes?.clientes?.id||sedes.find(s=>s.id===periodoObjetivo.sede_id)?.cliente_id,supervisor_registro_id:user.id,tipo_marcacion_id:tipo.id,horas:tipo.clase==='HORAS'?Number(form.horas):0,es_cobertura:!!form.es_cobertura,vinculo_cubierto_id:form.vinculo_cubierto_id?Number(form.vinculo_cubierto_id):null,motivo_cobertura:form.es_cobertura?form.motivo_cobertura:null,observacion:form.observacion||null,actualizado_por_id:user.id};
    const request=modal.edicion ? supabase.from("tareo_marcaciones").update(payload).eq("id",modal.edicion.id) : supabase.from("tareo_marcaciones").insert({...payload,creado_por_id:user.id});
    const {error:err}=await request; if(err) throw err; setModal(null); setForm({tipo:"HORAS",horas:8,es_cobertura:false,motivo_cobertura:"",observacion:"",vinculo_cubierto_id:""}); if(vistaCliente) await abrirCliente(); else await abrirPeriodo(periodoObjetivo);
  } catch(e:any) { setError(e.message); } finally { setLoading(false); } };
  const cambiarEstado = async (accion:string) => { if(!periodo) return; const observacion=(accion==='observar'?prompt("Observación para el supervisor:") : null); if(accion==='observar'&&!observacion) return; const {data,error:err}=await supabase.rpc("tareo_cambiar_estado",{p_periodo_id:periodo.id,p_accion:accion,p_observacion:observacion}); if(err) setError(err.message); else { setPeriodo(data); setPeriodos(periodos.map(p=>p.id===data.id?data:p)); } };
  const enviarPeriodosCliente = async () => { const pendientes=periodosCliente.filter(p=>["Borrador","Observado","Corregido"].includes(p.estado)); if(!pendientes.length) return; setLoading(true); setError(""); try { for(const p of pendientes){const {error:err}=await supabase.rpc("tareo_cambiar_estado",{p_periodo_id:p.id,p_accion:"enviar"});if(err) throw err;} await abrirCliente(); } catch(e:any) { setError(e.message); } finally { setLoading(false); } };

  const mapa = useMemo(()=>{ const r=new Map<string,any[]>(); marcaciones.forEach(m=>{const k=`${m.vinculo_laboral_id}-${m.fecha}`;r.set(k,[...(r.get(k)||[]),m]);});return r;},[marcaciones]);
  const mapaCliente = useMemo(()=>{ const r=new Map<string,any[]>(); marcacionesCliente.forEach(m=>{const k=`${m.periodo_id}-${m.vinculo_laboral_id}-${m.fecha}`;r.set(k,[...(r.get(k)||[]),m]);});return r;},[marcacionesCliente]);
  const exportar = () => { if(!periodo) return; const d=diasEnMes(periodo.mes,periodo.anio); const headers=["N°","EMPRESA","UNIDAD","HORAS","PERIODO","TURNO","APELLIDOS Y NOMBRES","CARGO","DNI",...Array.from({length:d},(_,i)=>String(i+1)),"DIAS LABORADOS","DESCANSO","DFE","FI","FJ","DM","PSG","PCG","L","V","R","TOTAL DÍAS","TOTAL HORAS","OBSERVACIONES"];
    const rows=personal.map((v,i)=>{ const ms=marcaciones.filter(m=>m.vinculo_laboral_id===v.id); const codes=(c:string)=>ms.filter(m=>m.tipos_marcacion?.codigo===c).length; const hs=ms.reduce((s,m)=>s+Number(m.horas||0),0); const cells=Array.from({length:d},(_,x)=>{const xms=mapa.get(`${v.id}-${anio}-${fmt(mes)}-${fmt(x+1)}`)||[];return xms.map(m=>m.tipos_marcacion?.codigo==='HORAS'?m.horas:m.tipos_marcacion?.codigo).join("+")||""}); const days=ms.filter(m=>Number(m.horas)>0).length; return [i+1,"",periodo.sedes?.nombre,"","", "",`${v.personas?.apellidos||""} ${v.personas?.nombres||""}`,v.cargos?.nombre||"",v.personas?.numero_documento||"",...cells,days,codes("D"),codes("DFE"),codes("FI"),codes("FJ"),codes("DM"),codes("PSG"),codes("PCG"),codes("L"),codes("V"),codes("R"),days+codes("D")+codes("DFE"),hs,ms.map(m=>m.observacion).filter(Boolean).join(" | ")]; });
    const ws=XLSX.utils.aoa_to_sheet([["TAREAJE MENSUAL"],[`RESPONSABLE: ${user?.nombres||""} ${user?.apellidos||""}`],[`${meses[mes-1]} ${anio} — ${periodo.sedes?.nombre||""}`],[],headers,...rows]); ws["!freeze"]={xSplit:9,ySplit:5}; ws["!cols"]=headers.map((h,i)=>({wch:i<9?18:i<9+d?5:12})); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,`T.${meses[mes-1].slice(0,3)}${String(anio).slice(-2)}`); const sum=XLSX.utils.json_to_sheet(rows.map((r:any)=>({Trabajador:r[6],Horas:r[r.length-2],Observaciones:r[r.length-1]}))); XLSX.utils.book_append_sheet(wb,sum,"Consolidado"); XLSX.writeFile(wb,`tareaje_${periodo.sedes?.nombre||periodo.sede_id}_${mes}_${anio}.xlsx`); };
  const personasMostradas = useMemo(()=>{ const ids=new Set(personal.map(v=>v.id)); const externos=marcaciones.flatMap(m=>{if(!ids.has(m.vinculo_laboral_id)&&m.vinculos_laborales){ids.add(m.vinculo_laboral_id);return [m.vinculos_laborales];} return [];}); return [...personal,...externos];},[personal,marcaciones]);
  const consultaMovil = periodo && <section className="tareo-mobile-summary lg:hidden space-y-3" aria-label="Consulta móvil de tareo">
    <div className="rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="text-sm font-bold text-blue-900">Consulta de tareo</p><p className="mt-1 text-xs text-blue-700">{periodo.sedes?.nombre} · {meses[mes-1]} {anio} · {periodo.estado}</p><p className="mt-2 text-[11px] text-blue-700">La edición de días y las coberturas se realizan desde PC.</p></div>
    {personasMostradas.map(v => { const ms=marcaciones.filter(m=>m.vinculo_laboral_id===v.id); const horas=ms.reduce((s,m)=>s+Number(m.horas||0),0); const alertas=ms.flatMap(m=>m.alertas||[]).length; return <article key={v.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-3"><div><p className="font-bold text-sm text-slate-800">{v.personas?.apellidos} {v.personas?.nombres}</p><p className="mt-1 text-xs text-slate-500">{v.cargos?.nombre || "Sin cargo"}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{horas} h</span></div><p className="mt-3 text-xs text-slate-500">{ms.length} marcaciones{alertas ? ` · ${alertas} alertas` : ""}</p></article>; })}
  </section>;

  return <div className="tareo-page h-full flex flex-col gap-3 overflow-y-auto lg:overflow-hidden">
    {consultaMovil}
    <div className="bg-blue-50 border border-blue-100 rounded-xl px-4 py-3 flex flex-wrap items-end gap-3">
      <div className="min-w-72"><label className="text-[10px] font-bold text-blue-700">CLIENTE</label><select value={clienteId} onChange={e=>{setClienteId(e.target.value);setSedeId("");setPeriodo(null);setVistaCliente(false);}} className="block border border-blue-200 rounded p-2 text-sm w-full bg-white"><option value="">Seleccione un cliente...</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></div>
      <button onClick={abrirCliente} disabled={loading||!clienteId} className="bg-blue-600 text-white rounded px-4 py-2 text-sm font-bold">Ver todas las sedes</button>
      {vistaCliente && <button onClick={enviarPeriodosCliente} disabled={loading} className="bg-emerald-600 text-white rounded px-4 py-2 text-sm font-bold flex gap-2"><Send className="w-4 h-4"/>Enviar sedes en borrador</button>}
      {clienteId && <span className="text-xs text-blue-700">Seleccione una sede abajo para abrir su tareo individual.</span>}
    </div>
    {vistaCliente && <div className="flex-1 bg-white border rounded-xl overflow-auto"><div className="p-4 border-b sticky top-0 bg-white z-10"><h2 className="font-bold text-slate-800">Tareo conjunto — {clientes.find(c=>String(c.id)===clienteId)?.nombre}</h2><p className="text-xs text-slate-500 mt-1">Se cargaron todas las sedes asignadas a este supervisor. Cada bloque conserva su propia sede y estado.</p></div>{periodosCliente.map(p=>{const equipo=personalCliente.filter(v=>v.sede_id===p.sede_id);const puedeEditar=puedeEditarPeriodo(p);return <section key={p.id} className="border-b last:border-0"><div className="bg-slate-800 text-white px-4 py-2 font-bold text-sm flex justify-between"><span>{p.sedes?.clientes?.razon_social || clientes.find(c=>String(c.id)===clienteId)?.nombre} — {p.sedes?.nombre}</span><span className="text-xs bg-white/15 px-2 py-0.5 rounded">{p.estado}</span></div><table className="text-xs border-collapse min-w-[1450px] w-full"><thead className="bg-slate-100 text-slate-700"><tr><th className="p-1 text-left w-72">Trabajador</th><th className="p-1 text-left w-48">Cargo</th>{Array.from({length:diasEnMes(mes,anio)},(_,i)=><th key={i} className="p-1 text-center border-l w-9"><span className="block font-bold">{i+1}</span><span className="block text-[9px] uppercase">{new Date(anio,mes-1,i+1).toLocaleDateString("es-PE",{weekday:"short"}).replace(".","")}</span></th>)}<th className="p-1 text-center">Horas</th></tr></thead><tbody>{equipo.map(v=>{const ms=marcacionesCliente.filter(m=>m.periodo_id===p.id&&m.vinculo_laboral_id===v.id);return <tr key={v.id} className="border-b hover:bg-slate-50"><td className="p-2 w-72 font-bold">{v.personas?.apellidos} {v.personas?.nombres}</td><td className="p-2 w-48 text-slate-500">{v.cargos?.nombre}</td>{Array.from({length:diasEnMes(mes,anio)},(_,i)=>{const fecha=`${anio}-${fmt(mes)}-${fmt(i+1)}`;const xs=mapaCliente.get(`${p.id}-${v.id}-${fecha}`)||[];return <td key={fecha} className="p-1 text-center border-l w-9">{xs.length?<button title="Editar marcación" onClick={()=>{const x=xs[0];setModal({...v,fecha,periodo:p,edicion:x});setForm({tipo:x.tipos_marcacion?.codigo||"HORAS",horas:x.horas||8,es_cobertura:!!x.es_cobertura,motivo_cobertura:x.motivo_cobertura||"",observacion:x.observacion||"",vinculo_cubierto_id:x.vinculo_cubierto_id||""});}} className="font-bold text-blue-700">{xs.map(x=>x.tipos_marcacion?.codigo==='HORAS'?x.horas:x.tipos_marcacion?.codigo).join("+")}</button>:puedeEditar?<button onClick={()=>{setModal({...v,fecha,periodo:p});setForm({tipo:"HORAS",horas:8,es_cobertura:false,motivo_cobertura:"",observacion:"",vinculo_cubierto_id:""});}} className="text-blue-500"><Plus className="w-3 h-3"/></button>:"—"}</td>})}<td className="p-2 font-bold">{ms.reduce((s,m)=>s+Number(m.horas||0),0)}</td></tr>})}</tbody></table></section>})}</div>}
    <div className="bg-white border rounded-xl p-4 flex flex-wrap gap-3 items-end"><div><label className="text-[10px] font-bold text-slate-500">MES</label><select value={mes} onChange={e=>setMes(Number(e.target.value))} className="block border rounded p-2 text-sm">{meses.map((x,i)=><option key={x} value={i+1}>{x}</option>)}</select></div><div><label className="text-[10px] font-bold text-slate-500">AÑO</label><input type="number" value={anio} onChange={e=>setAnio(Number(e.target.value))} className="block border rounded p-2 w-24 text-sm" /></div><div className="min-w-56"><label className="text-[10px] font-bold text-slate-500">SEDE</label><select value={sedeId} onChange={e=>{setSedeId(e.target.value);setVistaCliente(false);}} className="block border rounded p-2 text-sm w-full"><option value="">Todas las sedes del cliente</option>{sedesFiltradas.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select></div><button onClick={seleccionar} disabled={loading||(!sedeId&&!clienteId)} className="bg-blue-600 text-white rounded px-4 py-2 text-sm font-bold">{sedeId?(periodo?"Abrir":"Crear / abrir"):"Ver cliente"}</button><button onClick={cargarBase} className="p-2 border rounded"><RefreshCw className="w-4 h-4"/></button>{periodo&&<><span className="px-3 py-2 rounded bg-slate-100 text-xs font-bold">{periodo.estado}</span><button onClick={exportar} className="ml-auto border rounded px-3 py-2 text-xs font-bold flex gap-2"><Download className="w-4 h-4"/>Excel</button></>}</div>
    {error&&<div className="bg-red-50 text-red-700 border border-red-200 rounded p-3 text-sm flex gap-2"><AlertTriangle className="w-4 h-4"/>{error}<button className="ml-auto" onClick={()=>setError("")}><X className="w-4 h-4"/></button></div>}
    {!vistaCliente && (periodo?<div className="flex-1 bg-white border rounded-xl overflow-auto"><table className="text-xs border-collapse min-w-[1500px] w-full"><thead className="sticky top-0 bg-slate-800 text-white"><tr><th className="p-2 text-left sticky left-0 bg-slate-800">Trabajador</th><th className="p-2">Cargo</th>{Array.from({length:diasEnMes(mes,anio)},(_,i)=><th key={i} className="p-2">{i+1}<br/><span className="font-normal">{new Date(anio,mes-1,i+1).toLocaleDateString("es-PE",{weekday:"narrow"})}</span></th>)}<th className="p-2">Horas</th><th className="p-2">Alertas</th></tr></thead><tbody>{personasMostradas.map(v=>{const ms=marcaciones.filter(m=>m.vinculo_laboral_id===v.id);return <tr key={v.id} className="border-b hover:bg-slate-50"><td className="p-2 sticky left-0 bg-white font-bold">{v.personas?.apellidos} {v.personas?.nombres}<div className="text-[9px] text-slate-400">{v.sedes?.nombre!==periodo.sedes?.nombre?"Cobertura externa":""}</div></td><td className="p-2">{v.cargos?.nombre}</td>{Array.from({length:diasEnMes(mes,anio)},(_,i)=>{const fecha=`${anio}-${fmt(mes)}-${fmt(i+1)}`;const xs=mapa.get(`${v.id}-${fecha}`)||[];return <td key={fecha} className="p-1 text-center border-l">{xs.length?<button title="Editar marcación" onClick={()=>{const x=xs[0];setModal({...v,fecha,edicion:x});setForm({tipo:x.tipos_marcacion?.codigo||"HORAS",horas:x.horas||8,es_cobertura:!!x.es_cobertura,motivo_cobertura:x.motivo_cobertura||"",observacion:x.observacion||"",vinculo_cubierto_id:x.vinculo_cubierto_id||""});}} className="font-bold text-blue-700 hover:bg-blue-50 rounded px-1">{xs.map(x=>x.tipos_marcacion?.codigo==='HORAS'?x.horas:x.tipos_marcacion?.codigo).join("+")}</button>:editable?<button onClick={()=>{setModal({...v,fecha});setForm({...form});}} className="text-blue-500 hover:bg-blue-50 rounded px-1"><Plus className="w-3 h-3"/></button>:"—"}</td>})}<td className="p-2 font-bold">{ms.reduce((s,m)=>s+Number(m.horas||0),0)}</td><td className="p-2 text-amber-600">{ms.flatMap(m=>m.alertas||[]).length||""}</td></tr>})}</tbody></table></div>:<div className="flex-1 grid place-items-center text-slate-400"><FileSpreadsheet className="w-10 h-10"/><p>Seleccione una sede y periodo para iniciar.</p></div>)}
    {periodo&&<div className="bg-white border rounded-xl p-3 flex gap-2 justify-end">{editable&&<button onClick={()=>cambiarEstado("enviar")} className="bg-blue-600 text-white px-4 py-2 rounded text-xs font-bold flex gap-2"><Send className="w-4 h-4"/>Enviar a Planilla</button>}{esPlanilla&&["Enviado","Corregido"].includes(periodo.estado)&&<><button onClick={()=>cambiarEstado("observar")} className="border border-amber-300 text-amber-700 px-4 py-2 rounded text-xs font-bold">Observar</button><button onClick={()=>cambiarEstado("aprobar")} className="bg-emerald-600 text-white px-4 py-2 rounded text-xs font-bold flex gap-2"><Check className="w-4 h-4"/>Aprobar</button></>}{esPlanilla&&periodo.estado==="Aprobado"&&<button onClick={()=>cambiarEstado("cerrar")} className="bg-slate-800 text-white px-4 py-2 rounded text-xs font-bold">Cerrar periodo</button>}</div>}
    {editable&&<div className="flex justify-start"><button onClick={abrirCobertura} className="border border-blue-200 bg-blue-50 text-blue-700 px-4 py-2 rounded text-xs font-bold flex gap-2"><Plus className="w-4 h-4"/>Añadir cobertura</button></div>}
    {coberturaPicker&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/40"><div className="bg-white rounded-xl shadow-xl p-5 w-full max-w-lg space-y-3"><div className="flex justify-between"><h3 className="font-bold">Añadir trabajador para cobertura</h3><button onClick={()=>setCoberturaPicker(false)}><X/></button></div><p className="text-xs text-slate-500">La sede principal del trabajador no se modificará.</p><input placeholder="Buscar por nombre o DNI" value={busquedaCobertura} onChange={e=>setBusquedaCobertura(e.target.value)} className="w-full border rounded p-2 text-sm"/><select size={7} value={coberturaVinculoId} onChange={e=>setCoberturaVinculoId(e.target.value)} className="w-full border rounded p-2 text-sm">{candidatosCobertura.filter(v=>`${v.personas?.nombres||""} ${v.personas?.apellidos||""} ${v.personas?.numero_documento||""}`.toLowerCase().includes(busquedaCobertura.toLowerCase())).map(v=><option key={v.id} value={v.id}>{v.personas?.apellidos} {v.personas?.nombres} — {v.sedes?.nombre || "Sin sede"}</option>)}</select><div><label className="text-[10px] font-bold text-slate-500">FECHA DE COBERTURA</label><input type="date" min={`${anio}-${fmt(mes)}-01`} max={`${anio}-${fmt(mes)}-${fmt(diasEnMes(mes,anio))}`} value={coberturaFecha} onChange={e=>setCoberturaFecha(e.target.value)} className="block w-full border rounded p-2"/></div><button onClick={iniciarCobertura} className="w-full bg-blue-600 text-white rounded p-2 font-bold">Continuar con la marcación</button></div></div>}
    {modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/40"><div className="bg-white rounded-xl shadow-xl p-5 w-full max-w-md space-y-3"><div className="flex justify-between"><h3 className="font-bold">Marcación {modal.fecha}</h3><button onClick={()=>setModal(null)}><X/></button></div><p className="text-sm">{modal.personas?.apellidos} {modal.personas?.nombres}</p><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} className="w-full border rounded p-2">{tipos.map(t=><option key={t.id} value={t.codigo}>{t.codigo} — {t.nombre}</option>)}</select>{form.tipo==="HORAS"&&<input type="number" min="0.5" max="24" step="0.5" value={form.horas} onChange={e=>setForm({...form,horas:e.target.value})} className="w-full border rounded p-2"/>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={form.es_cobertura} onChange={e=>setForm({...form,es_cobertura:e.target.checked})}/>Es cobertura</label>{form.es_cobertura&&<><select value={form.vinculo_cubierto_id} onChange={e=>setForm({...form,vinculo_cubierto_id:e.target.value})} className="w-full border rounded p-2 text-sm"><option value="">Puesto vacante / sin trabajador cubierto</option>{personal.map(v=><option key={v.id} value={v.id}>{v.personas?.apellidos} {v.personas?.nombres}</option>)}</select><input required placeholder="Motivo de cobertura" value={form.motivo_cobertura} onChange={e=>setForm({...form,motivo_cobertura:e.target.value})} className="w-full border rounded p-2"/></>}<textarea placeholder="Observación" value={form.observacion} onChange={e=>setForm({...form,observacion:e.target.value})} className="w-full border rounded p-2"/><button onClick={guardar} className="w-full bg-blue-600 text-white rounded p-2 font-bold">Guardar</button></div></div>}
  </div>;
}
