-- Módulo de tareo por sedes. Ejecutar en Supabase SQL Editor o con Supabase CLI.

alter table public.usuarios add column if not exists auth_user_id uuid unique references auth.users(id) on delete set null;
update public.usuarios u set auth_user_id = au.id from auth.users au
where u.auth_user_id is null and lower(u.correo) = lower(au.email);

insert into public.roles (codigo,nombre,descripcion)
select 'planilla','Planilla','Revisa, aprueba y cierra tareos mensuales.'
where not exists (select 1 from public.roles where codigo='planilla');

create table if not exists public.tipos_marcacion (
  id bigint generated by default as identity primary key, codigo varchar(20) not null unique,
  nombre varchar(120) not null, clase varchar(20) not null check (clase in ('HORAS','NOVEDAD')),
  activo boolean not null default true, es_legacy boolean not null default false, creado_en timestamptz not null default now()
);
insert into public.tipos_marcacion(codigo,nombre,clase,es_legacy) values
('HORAS','Horas trabajadas','HORAS',false),('D','Descanso laboral','NOVEDAD',false),('DFE','Descanso por feriado','NOVEDAD',false),('FI','Falta injustificada','NOVEDAD',false),('FJ','Falta justificada','NOVEDAD',false),('P','Permiso solicitado anticipadamente','NOVEDAD',false),('PSG','Permiso sin goce','NOVEDAD',false),('PCG','Permiso con goce','NOVEDAD',false),('DM','Descanso médico','NOVEDAD',false),('L','Licencia','NOVEDAD',false),('V','Vacaciones','NOVEDAD',false),('R','Renuncia o retiro','NOVEDAD',false),('.--','No programado','NOVEDAD',false),('PG','Permiso con goce (legado)','NOVEDAD',true),('S','Suspendido (legado)','NOVEDAD',true),('TS','Trabajador suspendido (legado)','NOVEDAD',true),('TC','Término de contrato (legado)','NOVEDAD',true),('CPP','Cancelación periodo prueba (legado)','NOVEDAD',true),('Ab','Abandono de trabajo (legado)','NOVEDAD',true),('Base','Retén base (legado)','NOVEDAD',true)
on conflict(codigo) do update set nombre=excluded.nombre,clase=excluded.clase,es_legacy=excluded.es_legacy;

create table if not exists public.tareo_configuracion (
 id bigint generated by default as identity primary key, empresa_interna_id int references public.empresas_internas(id) on delete cascade,
 limite_horas_diarias numeric(5,2) not null default 16 check(limite_horas_diarias between 1 and 24),
 limite_jornada_inusual numeric(5,2) not null default 12 check(limite_jornada_inusual between 1 and 24), unique nulls not distinct(empresa_interna_id)
);
create table if not exists public.tareo_periodos (
 id bigint generated by default as identity primary key, sede_id int not null references public.sedes(id) on delete restrict,
 mes smallint not null check(mes between 1 and 12), anio smallint not null check(anio between 2020 and 2100),
 supervisor_responsable_id int not null references public.usuarios(id) on delete restrict,
 estado varchar(20) not null default 'Borrador' check(estado in ('Borrador','Enviado','Observado','Corregido','Aprobado','Cerrado')),
 observaciones text, enviado_en timestamptz, enviado_por_id int references public.usuarios(id), aprobado_en timestamptz, aprobado_por_id int references public.usuarios(id), cerrado_en timestamptz, cerrado_por_id int references public.usuarios(id), creado_en timestamptz not null default now(), actualizado_en timestamptz not null default now(), unique(sede_id,mes,anio)
);
create table if not exists public.tareo_marcaciones (
 id bigint generated by default as identity primary key, periodo_id bigint not null references public.tareo_periodos(id) on delete cascade,
 vinculo_laboral_id int not null references public.vinculos_laborales(id) on delete restrict, fecha date not null,
 sede_trabajada_id int not null references public.sedes(id) on delete restrict, cliente_id int not null references public.clientes(id) on delete restrict,
 supervisor_registro_id int not null references public.usuarios(id), tipo_marcacion_id bigint not null references public.tipos_marcacion(id), horas numeric(5,2) not null default 0 check(horas between 0 and 24),
 es_cobertura boolean not null default false, vinculo_cubierto_id int references public.vinculos_laborales(id) on delete set null, motivo_cobertura text, observacion text, alertas jsonb not null default '[]'::jsonb,
 creado_en timestamptz not null default now(), creado_por_id int not null references public.usuarios(id), actualizado_en timestamptz not null default now(), actualizado_por_id int not null references public.usuarios(id),
 check((es_cobertura and nullif(trim(coalesce(motivo_cobertura,'')),'') is not null) or not es_cobertura)
);
create unique index if not exists tareo_marcaciones_duplicado_exacto on public.tareo_marcaciones(periodo_id,vinculo_laboral_id,fecha,sede_trabajada_id,tipo_marcacion_id,horas,coalesce(vinculo_cubierto_id,-1),coalesce(motivo_cobertura,''));
create index if not exists tareo_marcaciones_fecha_idx on public.tareo_marcaciones(periodo_id,fecha,vinculo_laboral_id);
create table if not exists public.tareo_auditoria (
 id bigint generated by default as identity primary key, periodo_id bigint not null references public.tareo_periodos(id) on delete cascade, marcacion_id bigint references public.tareo_marcaciones(id) on delete set null,
 accion varchar(30) not null, valor_anterior jsonb, valor_nuevo jsonb, usuario_id int references public.usuarios(id) on delete set null, motivo text, estado_periodo varchar(20), creado_en timestamptz not null default now()
);

create or replace function public.tareo_usuario_actual_id() returns int language sql stable security definer set search_path=public as $$ select id from public.usuarios where activo and (auth_user_id=auth.uid() or lower(correo)=lower(coalesce(auth.jwt()->>'email',''))) limit 1 $$;
create or replace function public.tareo_rol_actual() returns text language sql stable security definer set search_path=public as $$ select r.codigo from public.usuarios u join public.roles r on r.id=u.rol_id where u.id=public.tareo_usuario_actual_id() $$;
create or replace function public.tareo_es_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.tareo_rol_actual() in ('admin','gerencia'),false) $$;
create or replace function public.tareo_puede_operar_sede(p_sede_id int) returns boolean language sql stable security definer set search_path=public as $$ select public.tareo_es_admin() or exists(select 1 from public.usuario_sedes where usuario_id=public.tareo_usuario_actual_id() and sede_id=p_sede_id) $$;

create or replace function public.tareo_validar_marcacion() returns trigger language plpgsql security definer set search_path=public as $$
declare p public.tareo_periodos; v public.vinculos_laborales; v_clase text; total_horas numeric; avisos jsonb:='[]'::jsonb;
begin
 select * into p from public.tareo_periodos where id=new.periodo_id; if p is null then raise exception 'Periodo no encontrado'; end if;
 if new.fecha < make_date(p.anio,p.mes,1) or new.fecha > (make_date(p.anio,p.mes,1)+interval '1 month - 1 day')::date then raise exception 'La fecha no pertenece al periodo'; end if;
 if p.estado not in ('Borrador','Observado','Corregido') then raise exception 'El periodo está bloqueado'; end if;
 if new.sede_trabajada_id<>p.sede_id or not public.tareo_puede_operar_sede(new.sede_trabajada_id) then raise exception 'No tiene acceso a la sede trabajada'; end if;
 select * into v from public.vinculos_laborales where id=new.vinculo_laboral_id; if v.fecha_cese is not null and new.fecha>v.fecha_cese then raise exception 'No se permiten horas posteriores al cese'; end if;
 select tm.clase into v_clase from public.tipos_marcacion tm where tm.id=new.tipo_marcacion_id and tm.activo; if v_clase is null or ((v_clase='HORAS')<>(new.horas>0)) then raise exception 'Tipo u horas de marcación inválidos'; end if;
 if exists(select 1 from public.vacaciones_historico where vinculo_laboral_id=new.vinculo_laboral_id and new.fecha between fecha_inicio and fecha_fin) and new.horas>0 then avisos:=avisos||jsonb_build_array('Horas registradas durante vacaciones'); end if;
 select coalesce(sum(horas),0) into total_horas from public.tareo_marcaciones where vinculo_laboral_id=new.vinculo_laboral_id and fecha=new.fecha and id is distinct from new.id; if total_horas+new.horas>16 then avisos:=avisos||jsonb_build_array('Jornada diaria inusual'); end if;
 new.cliente_id:=(select cliente_id from public.sedes where id=new.sede_trabajada_id); new.supervisor_registro_id:=public.tareo_usuario_actual_id(); new.actualizado_por_id:=public.tareo_usuario_actual_id(); new.actualizado_en:=now(); new.alertas:=avisos;
 if tg_op='INSERT' then new.creado_por_id:=public.tareo_usuario_actual_id(); new.creado_en:=now(); end if; return new;
end $$;
drop trigger if exists trg_tareo_validar_marcacion on public.tareo_marcaciones;
create trigger trg_tareo_validar_marcacion before insert or update on public.tareo_marcaciones for each row execute function public.tareo_validar_marcacion();

create or replace function public.tareo_auditar_marcacion() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.tareo_auditoria(periodo_id,marcacion_id,accion,valor_anterior,valor_nuevo,usuario_id,estado_periodo) values(coalesce(new.periodo_id,old.periodo_id),coalesce(new.id,old.id),tg_op,to_jsonb(old),to_jsonb(new),public.tareo_usuario_actual_id(),(select estado from public.tareo_periodos where id=coalesce(new.periodo_id,old.periodo_id))); return coalesce(new,old); end $$;
drop trigger if exists trg_tareo_auditar_marcacion on public.tareo_marcaciones;
create trigger trg_tareo_auditar_marcacion after insert or update or delete on public.tareo_marcaciones for each row execute function public.tareo_auditar_marcacion();

create or replace function public.tareo_cambiar_estado(p_periodo_id bigint,p_accion text,p_observacion text default null,p_motivo text default null) returns public.tareo_periodos language plpgsql security definer set search_path=public as $$
declare p public.tareo_periodos; u int:=public.tareo_usuario_actual_id(); rol text:=public.tareo_rol_actual(); siguiente text;
begin select * into p from public.tareo_periodos where id=p_periodo_id for update; if p is null then raise exception 'Periodo no encontrado'; end if;
 siguiente:=case p_accion when 'enviar' then case when p.estado='Borrador' then 'Enviado' when p.estado='Observado' then 'Corregido' when p.estado='Corregido' then 'Enviado' end when 'observar' then case when p.estado in ('Enviado','Corregido') and rol in ('planilla','admin') then 'Observado' end when 'aprobar' then case when p.estado in ('Enviado','Corregido') and rol in ('planilla','admin') then 'Aprobado' end when 'cerrar' then case when p.estado='Aprobado' and rol in ('planilla','admin') then 'Cerrado' end when 'reabrir' then case when p.estado in ('Aprobado','Cerrado') and rol='admin' then 'Borrador' end end;
 if siguiente is null then raise exception 'Transición no permitida'; end if; if p_accion='reabrir' and nullif(trim(coalesce(p_motivo,'')),'') is null then raise exception 'La reapertura requiere motivo'; end if;
 update public.tareo_periodos set estado=siguiente,observaciones=coalesce(p_observacion,observaciones),enviado_en=case when siguiente='Enviado' then now() else enviado_en end,enviado_por_id=case when siguiente='Enviado' then u else enviado_por_id end,aprobado_en=case when siguiente='Aprobado' then now() else aprobado_en end,aprobado_por_id=case when siguiente='Aprobado' then u else aprobado_por_id end,cerrado_en=case when siguiente='Cerrado' then now() else cerrado_en end,cerrado_por_id=case when siguiente='Cerrado' then u else cerrado_por_id end,actualizado_en=now() where id=p_periodo_id returning * into p;
 insert into public.tareo_auditoria(periodo_id,accion,usuario_id,motivo,estado_periodo) values(p.id,upper(p_accion),u,coalesce(p_motivo,p_observacion),p.estado); return p;
end $$;

create or replace view public.v_tareo_consolidado as
select tm.periodo_id,tp.anio,tp.mes,tm.vinculo_laboral_id,vl.persona_id,tm.sede_trabajada_id,tm.cliente_id,sum(tm.horas) total_horas,count(distinct tm.fecha) filter(where tm.horas>0) dias_laborados,count(*) filter(where t.codigo='D') descansos,count(*) filter(where t.codigo='DFE') descansos_feriado,count(*) filter(where t.codigo='FI') faltas_injustificadas,count(*) filter(where t.codigo='FJ') faltas_justificadas,count(*) filter(where t.codigo in ('P','PSG','PCG','PG')) permisos,count(*) filter(where t.codigo='DM') descansos_medicos,count(*) filter(where t.codigo='V') vacaciones,count(*) filter(where t.codigo='R') retiros,count(*) filter(where t.codigo='.--') no_programados,sum(tm.horas) filter(where tm.es_cobertura) horas_cobertura
from public.tareo_marcaciones tm join public.tareo_periodos tp on tp.id=tm.periodo_id join public.vinculos_laborales vl on vl.id=tm.vinculo_laboral_id join public.tipos_marcacion t on t.id=tm.tipo_marcacion_id
group by tm.periodo_id,tp.anio,tp.mes,tm.vinculo_laboral_id,vl.persona_id,tm.sede_trabajada_id,tm.cliente_id;

alter table public.tareo_periodos enable row level security; alter table public.tareo_marcaciones enable row level security; alter table public.tareo_auditoria enable row level security; alter table public.tipos_marcacion enable row level security; alter table public.tareo_configuracion enable row level security;
create policy "tareo_periodos_select" on public.tareo_periodos for select using(public.tareo_es_admin() or public.tareo_rol_actual()='planilla' or public.tareo_puede_operar_sede(sede_id));
create policy "tareo_periodos_insert" on public.tareo_periodos for insert with check(public.tareo_puede_operar_sede(sede_id) and supervisor_responsable_id=public.tareo_usuario_actual_id());
create policy "tareo_periodos_update" on public.tareo_periodos for update using(public.tareo_es_admin() or (public.tareo_puede_operar_sede(sede_id) and supervisor_responsable_id=public.tareo_usuario_actual_id() and estado in ('Borrador','Observado','Corregido')));
create policy "tareo_marcaciones_access" on public.tareo_marcaciones for all using(exists(select 1 from public.tareo_periodos p where p.id=periodo_id and (public.tareo_es_admin() or public.tareo_rol_actual()='planilla' or public.tareo_puede_operar_sede(p.sede_id)))) with check(public.tareo_puede_operar_sede(sede_trabajada_id));
create policy "tareo_catalogos_select" on public.tipos_marcacion for select using(true);
create policy "tareo_config_select" on public.tareo_configuracion for select using(public.tareo_es_admin() or public.tareo_rol_actual()='planilla');
create policy "tareo_auditoria_select" on public.tareo_auditoria for select using(public.tareo_es_admin() or public.tareo_rol_actual()='planilla' or exists(select 1 from public.tareo_periodos p where p.id=periodo_id and public.tareo_puede_operar_sede(p.sede_id)));
